/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';
import type {
  AccountSubtype,
  AccountType,
  ActorType,
  EntryDirection,
  KycStatus,
  LedgerTransactionStatus,
  LimitType,
  PaymentMethod,
  PaymentProvider,
  PaymentStatus,
  ReconciliationStatus,
  SettlementBatchStatus,
  TransactionDirection,
  TransactionStatus,
  TransactionType,
  UserRole,
  WebhookEventStatus,
  WebhookProvider,
} from '../utils/database.enums';

export type Accountsubtype = AccountSubtype;
export type Accounttype = AccountType;
export type Actortype = ActorType;
export type Entrydirection = EntryDirection;
export type Kycstatus = KycStatus;

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<
  string,
  bigint | number | string,
  bigint | number | string
>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Ledgertransactionstatus = LedgerTransactionStatus;
export type Limittype = LimitType;
export type Paymentmethod = PaymentMethod;
export type Paymentprovider = PaymentProvider;
export type Paymentstatus = PaymentStatus;
export type Reconciliationstatus = ReconciliationStatus;
export type Settlementbatchstatus = SettlementBatchStatus;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type Transactiondirection = TransactionDirection;
export type Transactionstatus = TransactionStatus;
export type Transactiontype = TransactionType;
export type Userrole = UserRole;
export type Webhookeventstatus = WebhookEventStatus;
export type Webhookprovider = WebhookProvider;

export interface Accounts {
  availableBalance: Generated<Int8>;
  balance: Generated<Int8>;
  code: string;
  createdAt: Generated<Timestamp>;
  currency: Generated<string>;
  freezeReason: string | null;
  frozenAt: Timestamp | null;
  id: string;
  isActive: Generated<boolean>;
  name: string;
  subtype: Accountsubtype | null;
  type: Accounttype;
  updatedAt: Timestamp;
  userId: string | null;
  version: Generated<number>;
}

export interface AuditLogs {
  action: string;
  actorId: string | null;
  actorType: Actortype;
  after: Json | null;
  before: Json | null;
  correlationId: string | null;
  createdAt: Generated<Timestamp>;
  id: string;
  ipAddress: string | null;
  resourceId: string | null;
  resourceType: string;
  userAgent: string | null;
}

export interface Beneficiaries {
  accountName: string;
  accountNumber: string;
  bankCode: string;
  bankName: string | null;
  createdAt: Generated<Timestamp>;
  id: string;
  isActive: Generated<boolean>;
  isVerified: Generated<boolean>;
  nickname: string | null;
  updatedAt: Timestamp;
  userId: string;
  verifiedAt: Timestamp | null;
}

export interface KycProfiles {
  address: string;
  bvn: string;
  createdAt: Generated<Timestamp>;
  dateOfBirth: Timestamp;
  id: string;
  lga: string;
  nin: string;
  providerReference: string;
  rejectionReason: string;
  state: string;
  status: Generated<Kycstatus>;
  updatedAt: Timestamp;
  userId: string;
  verifiedAt: Timestamp;
}

export interface LedgerEntries {
  accountId: string;
  amount: Int8;
  currency: Generated<string>;
  description: string | null;
  direction: Entrydirection;
  id: string;
  transactionId: string;
}

export interface LedgerTransactions {
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: string;
  initiatedBy: string | null;
  metadata: Json | null;
  reference: string;
  reversalOfId: string | null;
  status: Generated<Ledgertransactionstatus>;
}

export interface Payments {
  amount: Int8;
  beneficiaryId: string | null;
  createdAt: Generated<Timestamp>;
  currency: string;
  description: string | null;
  externalReference: string | null;
  failureReason: string | null;
  feeAmount: Int8 | null;
  id: string;
  metadata: Json | null;
  netAmount: Int8 | null;
  nextRetryAt: Timestamp | null;
  paymentMethod: Paymentmethod;
  paymentReference: string;
  processedAt: Timestamp | null;
  provider: Generated<Paymentprovider>;
  retryCount: Generated<number>;
  status: Generated<Paymentstatus>;
  updatedAt: Timestamp;
  userId: string;
}

export interface ReconciliationItems {
  actualAmount: Int8 | null;
  createdAt: Generated<Timestamp>;
  discrepancyReason: string | null;
  expectedAmount: Int8;
  externalReference: string | null;
  id: string;
  paymentId: string | null;
  settlementBatchId: string;
  status: Generated<Reconciliationstatus>;
  transactionId: string | null;
  updatedAt: Timestamp;
}

export interface SettlementBatches {
  batchDate: Timestamp;
  createdAt: Generated<Timestamp>;
  externalBatchId: string | null;
  id: string;
  metadata: Json | null;
  provider: Paymentprovider;
  status: Generated<Settlementbatchstatus>;
  totalAmount: Int8;
  updatedAt: Timestamp;
}

export interface TransactionLimits {
  createdAt: Generated<Timestamp>;
  currency: Generated<string>;
  currentUsage: Generated<Int8>;
  id: string;
  kycTier: number | null;
  limitType: Limittype;
  maxAmount: Int8;
  periodStart: Generated<Timestamp>;
  updatedAt: Timestamp;
  userId: string | null;
}

export interface Transactions {
  amount: Int8;
  balanceAfter: Int8;
  balanceBefore: Int8;
  counterpartyAccount: string | null;
  counterpartyName: string | null;
  createdAt: Generated<Timestamp>;
  currency: string;
  description: string;
  direction: Transactiondirection;
  fee: Int8 | null;
  id: string;
  idempotencyKey: string;
  ledgerTransactionId: string | null;
  metadata: Json | null;
  paymentId: string | null;
  reconciled: Generated<boolean>;
  reconciledAt: Timestamp | null;
  reference: string;
  status: Generated<Transactionstatus>;
  type: Transactiontype;
  userId: string;
}

export interface Users {
  createdAt: Generated<Timestamp>;
  deletedAt: Timestamp | null;
  email: string;
  emailVerifiedAt: Timestamp | null;
  failedLoginAttempts: Generated<number>;
  firstName: string;
  id: string;
  isActive: Generated<boolean>;
  kycStatus: Generated<Kycstatus>;
  kycTier: Generated<number>;
  lastLoginAt: Timestamp | null;
  lastName: string;
  lockedUntil: Timestamp | null;
  password: string;
  phone: string;
  phoneVerifiedAt: Timestamp | null;
  pin: string | null;
  role: Generated<Userrole>;
  updatedAt: Timestamp;
}

export interface WebhookEvents {
  createdAt: Generated<Timestamp>;
  eventType: string;
  externalReference: string | null;
  failureReason: string | null;
  id: string;
  idempotencyKey: string;
  payload: Json;
  processedAt: Timestamp | null;
  provider: Webhookprovider;
  retryCount: Generated<number>;
  signature: string | null;
  status: Generated<Webhookeventstatus>;
  updatedAt: Timestamp;
}

export interface DB {
  accounts: Accounts;
  audit_logs: AuditLogs;
  beneficiaries: Beneficiaries;
  kyc_profiles: KycProfiles;
  ledger_entries: LedgerEntries;
  ledger_transactions: LedgerTransactions;
  payments: Payments;
  reconciliation_items: ReconciliationItems;
  settlement_batches: SettlementBatches;
  transaction_limits: TransactionLimits;
  transactions: Transactions;
  users: Users;
  webhook_events: WebhookEvents;
}
