FROM alpine:3.20

RUN apk add --no-cache bash curl gettext jq

WORKDIR /workspace

COPY infra/debezium ./infra/debezium

RUN chmod +x ./infra/debezium/register-transfer-outbox.sh

ENTRYPOINT ["./infra/debezium/register-transfer-outbox.sh"]
